name: mobilev
description: MobileV app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  path_provider: ^2.0.1
  just_audio: ^0.9.4
  record: ^3.0.0
  wakelock: ^0.5.2
  charts_flutter: ^0.11.0
  share_plus: ^2.1.4
  flutter_local_notifications: ^8.0.0
  flutter_native_timezone: ^2.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
    - family: PTMono
      fonts:
        - asset: assets/fonts/PTMono-Regular.ttf

flutter_app_name:
  name: "MobileV"